"""
state.py — Shared LangGraph state schema.

ResearchState is the single "truth object" that flows through every node in the
graph.  Each agent reads what it needs and writes back its results — no hidden
coupling between agents.
"""

from __future__ import annotations

from typing import Any, Optional
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class SourceRecord:
    """One retrieved web source."""
    url: str                         # Full URL of the page
    title: str                       # Page / article title
    snippet: str                     # Short excerpt (≤500 chars)
    full_content: str                # Full scraped text (may be truncated)
    relevance_score: float           # 1–10 score assigned by research agent
    retrieval_date: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    source_type: str = "unknown"     # Filled by classification agent
    domain: str = "general"         # Filled by classification agent
    relevance_tier: str = "medium"  # high / medium / low — classification agent


@dataclass
class EntityRecord:
    """A named entity extracted by the NER agent."""
    text: str           # Surface form, e.g. "OpenAI"
    label: str          # SpaCy label: ORG, PERSON, GPE, DATE, PRODUCT, …
    category: str       # Our higher-level: person/org/tech/date/location/concept
    count: int = 1      # How many times seen across all sources
    sources: list[str] = field(default_factory=list)  # URLs where it appears


@dataclass
class CostMetrics:
    """Running token and cost estimates for one research session."""
    input_tokens: int = 0
    output_tokens: int = 0
    # Approximate prices (USD per 1 M tokens) for claude-3-5-sonnet
    input_price_per_1m: float = 3.0
    output_price_per_1m: float = 15.0

    @property
    def estimated_cost_usd(self) -> float:
        return (
            self.input_tokens / 1_000_000 * self.input_price_per_1m
            + self.output_tokens / 1_000_000 * self.output_price_per_1m
        )

    def add(self, input_tokens: int, output_tokens: int) -> None:
        self.input_tokens += input_tokens
        self.output_tokens += output_tokens


@dataclass
class ResearchState:
    """
    Central state object shared across all LangGraph nodes.

    Every agent receives the full state and returns a dict with only the keys
    it modified — LangGraph merges the partial updates automatically.
    """

    # ── Input ─────────────────────────────────────────────────────────────────
    topic: str = ""
    # Sub-questions generated by the orchestrator to guide research
    sub_questions: list[str] = field(default_factory=list)

    # ── Research Agent output ─────────────────────────────────────────────────
    # All sources gathered from search + scraping before any filtering
    raw_sources: list[SourceRecord] = field(default_factory=list)

    # ── Classification Agent output ───────────────────────────────────────────
    # Sources after quality filtering; each has source_type, domain, relevance_tier
    classified_sources: list[SourceRecord] = field(default_factory=list)
    # Log entries explaining why sources were discarded
    classification_log: list[str] = field(default_factory=list)

    # ── NER Agent output ──────────────────────────────────────────────────────
    entities: list[EntityRecord] = field(default_factory=list)
    # Simple co-occurrence pairs: [("OpenAI", "GPT-4"), ...]
    entity_relationships: list[tuple[str, str]] = field(default_factory=list)
    # Maps entity text → list of source URLs where it appeared
    entity_source_map: dict[str, list[str]] = field(default_factory=dict)

    # ── Browser Agent output ──────────────────────────────────────────────────
    # Structured metadata and screenshots captured via Playwright
    browser_results: list[dict[str, Any]] = field(default_factory=list)

    # ── Analyzer Agent output ─────────────────────────────────────────────────
    # 4–6 synthesised themes derived from sources + NER
    themes: list[str] = field(default_factory=list)
    # Contradictions found between sources
    contradictions: list[str] = field(default_factory=list)
    # Evidence summary per theme
    evidence_summary: dict[str, str] = field(default_factory=dict)
    # Section outline for the writer
    outline: list[str] = field(default_factory=list)
    # Text prompts for the illustration agent
    image_prompts: list[str] = field(default_factory=list)
    # Transformer/AI architecture analysis specific context
    transformer_config: dict[str, Any] = field(default_factory=dict)
    # MoE (Mixture of Experts) comparison notes
    moe_analysis: dict[str, Any] = field(default_factory=dict)

    # ── Writer Agent output ───────────────────────────────────────────────────
    # Full Markdown report draft
    draft: str = ""
    # Numbered citation list to append to the report
    references: list[str] = field(default_factory=list)

    # ── Illustration Agent output ─────────────────────────────────────────────
    # Paths (relative to project root) of generated / placeholder images
    illustrations: list[str] = field(default_factory=list)

    # ── Critic Agent output ───────────────────────────────────────────────────
    critic_feedback: str = ""          # Natural-language critique
    critic_score: int = 0             # 1–10 rubric score
    critic_decision: str = "REVISE"   # "APPROVE" or "REVISE"

    # ── Revision loop ─────────────────────────────────────────────────────────
    revision_count: int = 0           # How many writer→critic loops so far

    # ── Final output ──────────────────────────────────────────────────────────
    final_report: str = ""            # The polished, approved Markdown report
    report_path: str = ""             # Path where the report was saved

    # ── Pipeline metadata ─────────────────────────────────────────────────────
    # Current pipeline status — displayed in the Streamlit progress bar
    status: str = "idle"
    # Non-fatal errors recorded during the run (never crash silently)
    errors: list[str] = field(default_factory=list)
    # Token and cost tracking
    cost_metrics: CostMetrics = field(default_factory=CostMetrics)
    # Wall-clock start time (ISO string)
    started_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
